### ISSUE TITLE
2 [feature] Добавить бота.

### ISSUE THREAD

**Issue by lev-slinsen** [lev-slinsen/DjangoPizzaShop#13]
Добавить уведомления о новом заказе через бота. Указывать аккаунты для уведомлений нужно в админке.

**Comment by lev-slinsen** [comment]
Непонятно, как узнавать ID чата. Надо как-то дать пользователю бота возможность получить свой ID. Например, сообщать его пользователю по команде /start.

**Comment by demoh2019** [comment]
после настройки бота и отправлении /start бот присылает id
